/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package statesandcapitalstesting;

public class Library {
//    public boolean someLibraryMethod() {
//        return true;
//    }
}
